### ISSUE TITLE
Finetuned BART checkpoints available?

### ISSUE THREAD

**Issue by DaehanKim** [tanyuqian/progressive-generation#6]
Hi Authors, Thanks for the great work. 
I want to run your BART models but no checkpoint seems available.
Are you planning to privide one? Thanks.

**Comment by tanyuqian** [comment]
Hi! Thanks a lot for noticing our work! 
Unfortunately, it has been two years since we run the experiments. We didn't keep our checkpoints, and we no longer have the access to those servers. You may need to run our training code to get models, I remember it just takes a couple of hours to run. Sorry for the inconvenience.

**Comment by DaehanKim** [comment]
codes are well written and functional. Thanks.
